apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-receiver-azdo.fullname" . }}
  labels:
    {{- include "alertmanager-receiver-azdo.labels" . | nindent 4 }}
data:
  appsettings.Production.json: {{ dict "settings" .Values.settings | toJson | b64enc | quote }}